runtime: java17
instance_class: F1

env_variables:
  SPRING_PROFILES_ACTIVE: "prod"
  JWT_SECRET: "prakruthi_homestay_secret_key_2024_secure_jwt_token"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 2

handlers:
- url: /.*
  script: auto
