[phases.setup]
aptPkgs = [
    "default-jdk",
    "maven"
]

[phases.install]
cmds = [
    "mvn dependency:go-offline"
]

[phases.build]
cmds = [
    "mvn clean package -DskipTests"
]

[start]
cmd = "java -jar target/*.jar"

[variables]
JAVA_HOME = "/usr/lib/jvm/java-17-openjdk-amd64"
MAVEN_OPTS = "-Xmx512m"
