app = "prakruthi-homestay-api"

[build]
builder = "nixpacks"

[deploy]
startCommand = "java -jar target/*.jar"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"

[env]
SPRING_PROFILES_ACTIVE = "prod"
PORT = "8080"
NIXPACKS_JDK_VERSION = "17"

[[build.steps]]
name = "Install Maven"
command = "apt-get update && apt-get install -y maven"

[[build.steps]]
name = "Build with Maven"
command = "mvn clean package -DskipTests"
