[build]
builder = "JAVA"
buildCommand = "mvn clean package -DskipTests"

[deploy]
startCommand = "java -jar target/*.jar"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"

[env]
SPRING_PROFILES_ACTIVE = "prod"
PORT = "8080"

[[phases.setup]]
nixPkgs = [
    "maven",
    "openjdk-17-jdk"
]

[[phases.install]]
cmds = [
    "mvn dependency:go-offline"
]

[[phases.build]]
cmds = [
    "mvn clean package -DskipTests"
]
