[build]
<<<<<<< Updated upstream
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "java -jar app.jar"
=======
builder = "NIXPACKS"
buildCommand = "mvn clean package -DskipTests"

[deploy]
startCommand = "java -jar target/*.jar"
>>>>>>> Stashed changes
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"

[env]
SPRING_PROFILES_ACTIVE = "prod"
PORT = "8080"
<<<<<<< Updated upstream
=======

[[phases.setup]]
name = "Install Maven"
aptPkgs = ["maven"]

[[phases.build]]
cmds = [
    "mvn clean package -DskipTests"
]

[[phases.deploy]]
cmds = [
    "java -jar target/*.jar"
]
>>>>>>> Stashed changes
