spring:
  profiles:
    active: dev
  data:
    mongodb:
      uri: mongodb+srv://prakruthi:Prakruthi1234@cluster0.kahoetc.mongodb.net/prakruthi_homestay
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080
  servlet:
    context-path: /api
  error:
    include-message: always

resend:
  api:
    key: re_MvptJ5X3_FS7xQWG1rZLUFkGtBCtuVkCh

razorpay:
  key:
    id: rzp_test_Nb4Z9WyKMSAjzu
    secret: cWLTHGXQ0h7sYckARPHYEkCJ

jwt:
  secret: ${JWT_SECRET:prakruthi_homestay_secret_key_2024_secure_jwt_token}
  expiration: 86400000 # 24 hours

app:
  cors:
    allowed-origins: 
      - http://localhost:3000
      - http://localhost:3001
      - https://prakruthi.vercel.app
      - https://prakruthi.srinovatech.site
  email:
    from: onboarding@resend.dev
    name: Prakruthi Homestay
  booking:
    check-in-time: "13:00"
    check-out-time: "11:00"
    min-advance-days: 1
    max-advance-days: 90
    base-price: 5000
  cancellation:
    free-days: 7
    partial-refund-days: 3
    partial-refund-percentage: 50
  villa:
    max-guests: 6
    min-stay: 1
    max-stay: 30

logging:
  level:
    root: INFO
    com.prakruthi.homestay: DEBUG
    org.springframework.security: INFO
    org.springframework.data.mongodb: INFO
